/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./models/model-walking.glb --shadows 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model-walking.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="walking">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
          <skinnedMesh name="ely_vanguardsoldier_kerwinatienza_Mesh001" geometry={nodes.ely_vanguardsoldier_kerwinatienza_Mesh001.geometry} material={materials['ely_vanguardsoldier_kerwinatienza_M2.001']} skeleton={nodes.ely_vanguardsoldier_kerwinatienza_Mesh001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-walking.glb')
